<template>
  <div v-if="!iv" class="empty-state"><div class="empty-icon">💬</div><div>請先選取訪談</div></div>
  <div v-else class="coding-workspace">
    <div class="interview-header"><div class="interview-meta"><div class="meta-chip">📁 <strong>{{ store.currentProject?.name }}</strong></div><div class="meta-chip">📋 <strong>{{ iv.title }}</strong></div><div class="meta-chip">💬 <strong>{{ segments.length }}</strong> 個片段</div></div><button class="btn btn-success btn-sm" :disabled="saving" @click="save">{{ saving ? '儲存中…' : '儲存逐字稿修訂' }}</button></div>
    <div class="coding-hint">{{ reselectCoding ? '請在原 Segment 重新選取相同文字，系統不會自動變更正式範圍。' : '選取單一對話氣泡中的非空文字，即可套用 Code。同一範圍可套用多個 Code。' }}</div>
    <div class="chat-area">
      <div v-for="seg in segments" :key="seg.id" class="chat-msg" :class="speaker(seg).side">
        <div class="segment-id">#{{ seg.source_reference || seg.display_order + 1 }} · v{{ seg.text_version }}</div>
        <div class="speaker-label" :style="labelStyle(seg)">{{ seg.speaker_name }}</div>
        <div class="bubble coding-bubble" :style="{ borderColor: speaker(seg).hex }" @mouseup="selectText(seg, $event)"><span v-for="(run,n) in runs(seg)" :key="n" class="coding-run" :class="{ 'has-coding': run.codings.length }" :style="runStyle(run)">{{ run.text }}</span></div>
        <div class="coding-chips"><span v-for="c in segmentCodings(seg.id)" :key="c.id" class="coding-chip" :class="{ 'needs-review': c.status === 'needs_review' }" :style="{ borderColor: code(c.code_id)?.color }"><span>{{ code(c.code_id)?.name }}</span><span v-if="c.status==='needs_review'">需重新確認</span><button v-if="c.status==='needs_review' && c.proposed_start != null" @click="reconfirm(c)">接受候選</button><button v-if="c.status==='needs_review'" @click="reselectCoding=c">手動重選</button><button @click="remove(c)">×</button></span></div>
        <textarea class="segment-editor" v-model="seg.text" aria-label="逐字稿文字"></textarea><textarea class="segment-note" v-model="seg.note" placeholder="Segment memo"></textarea>
      </div>
    </div>
  </div>
  <BaseModal :visible="Boolean(selection)" title="建立 Coding" @close="selection=null"><p class="selection-preview">「{{ selection?.text }}」</p><div class="form-group"><label class="form-label">Code</label><select class="form-select" v-model="codingForm.code_id"><option value="">請選擇</option><option v-for="c in activeCodes" :key="c.id" :value="c.id">{{ c.name }}</option></select></div><div class="form-group"><label class="form-label">Coding memo</label><textarea class="form-textarea" v-model="codingForm.memo"></textarea></div><button class="btn btn-primary" :disabled="!codingForm.code_id || creating" @click="create">建立 Coding</button></BaseModal>
</template>
<script setup>
import { ref, computed } from 'vue'; import { useAppStore } from '../stores/appStore.js'; import BaseModal from '../components/BaseModal.vue'; import { rangeRuns, selectionOffsets } from '../utils/textRanges.js'
const store=useAppStore(),saving=ref(false),creating=ref(false),selection=ref(null),reselectCoding=ref(null),codingForm=ref({code_id:'',memo:''}),iv=computed(()=>store.currentInterview),segments=computed(()=>store.currentSegments),activeCodes=computed(()=>store.codes.filter(c=>c.status==='active'))
function segmentCodings(id){return store.codings.filter(c=>c.segment_id===id)} function runs(seg){return rangeRuns(seg.text,segmentCodings(seg.id).filter(c=>c.status==='valid'))} function code(id){return store.codes.find(c=>c.id===id)} function speaker(seg){return store.speakerColorMap[seg.speaker_name]||{hex:'#6366f1',side:'left'}} function labelStyle(seg){const s=speaker(seg);return{background:s.hex+'22',color:s.hex,border:'1px solid '+s.hex+'44'}}
function runStyle(run){const colors=run.codings.map(c=>code(c.code_id)?.color).filter(Boolean);return colors.length?{background:colors[0]+'55',boxShadow:colors.slice(1).map((x,i)=>`inset 0 -${(i+1)*3}px ${x}`).join(',')}:{}} async function selectText(seg,event){const o=selectionOffsets(event.currentTarget,window.getSelection());if(!o)return;if(reselectCoding.value){if(reselectCoding.value.segment_id!==seg.id){store.toast('請在原 Segment 內重新選取','warning');return}try{await store.reconfirmCoding(reselectCoding.value,o.start,o.end);store.toast('Coding 已重新確認');reselectCoding.value=null}catch(e){store.toast('選取文字必須與原 Coding 文字相同','error')}return}selection.value={segment_id:seg.id,...o};codingForm.value={code_id:'',memo:''}}
async function create(){creating.value=true;try{await store.createCoding({segment_id:selection.value.segment_id,code_id:codingForm.value.code_id,start_offset:selection.value.start,end_offset:selection.value.end,memo:codingForm.value.memo});selection.value=null;store.toast('Coding 已建立')}finally{creating.value=false}} async function remove(c){await store.deleteCoding(c.id);store.toast('Coding 已移除')} async function reconfirm(c){await store.reconfirmCoding(c);store.toast('Coding 已重新確認')} async function save(){saving.value=true;try{await store.saveSegments([...segments.value]);store.toast('逐字稿已儲存；受影響 Coding 已標記')}finally{saving.value=false}}
</script>
