import { defineStore } from 'pinia'
import { api } from '../api/client.js'
import { useToast } from '../composables/useToast.js'
export const IV_HEX=['#6366f1','#8b5cf6','#06b6d4','#0ea5e9','#14b8a6'],IE_HEX=['#f97316','#ec4899','#84cc16','#f43f5e','#a855f7','#eab308','#10b981','#fb923c']

export const useAppStore=defineStore('app',{state:()=>({user:null,connectionStatus:'idle',projects:[],interviews:[],segments:[],codes:[],codings:[],cases:[],attributeDefinitions:[],currentProjectId:null,currentInterviewId:null,activeTab:'view',speakerColorMap:{},globalLoading:{show:false,message:''},confirmModal:{show:false,title:'',message:'',icon:'⚠️',okText:'確認',btnClass:'btn-danger',onConfirm:null}}),getters:{currentProject:s=>s.projects.find(p=>p.id===s.currentProjectId)||null,currentInterview:s=>s.interviews.find(i=>i.id===s.currentInterviewId)||null,currentSegments:s=>s.segments,projectInterviews:s=>id=>s.interviews.filter(i=>i.project_id===id)},actions:{
 async initialize(user){this.user=user;this.connectionStatus='loading';try{this.projects=await api('/v1/projects');this.connectionStatus='connected';if(this.projects[0])await this.selectProject(this.projects[0].id)}catch(e){this.connectionStatus='error';throw e}},
 clear(){this.$reset()},
 async selectProject(id){this.currentProjectId=id;this.currentInterviewId=null;this.segments=[];this.codings=[];[this.interviews,this.codes,this.cases,this.attributeDefinitions]=await Promise.all([api(`/v1/projects/${id}/interviews`),api(`/v1/projects/${id}/codes`),api(`/v1/projects/${id}/cases`),api(`/v1/projects/${id}/attribute-definitions`)]);if(this.interviews[0])await this.selectInterview(this.interviews[0].id)},
 async selectInterview(id){this.currentInterviewId=id;[this.segments,this.codings]=await Promise.all([api(`/v1/projects/${this.currentProjectId}/interviews/${id}/segments?limit=200`),api(`/v1/projects/${this.currentProjectId}/interviews/${id}/codings`)]);this.buildSpeakerColorMap(this.segments)},
 async saveProject(name,description=''){const p=await api('/v1/projects',{method:'POST',body:{name,description}});this.projects.unshift(p);await this.selectProject(p.id)},
 async deleteProject(id){await api(`/v1/projects/${id}`,{method:'DELETE'});this.projects=this.projects.filter(p=>p.id!==id);if(this.currentProjectId===id){this.currentProjectId=null;this.interviews=[];this.segments=[]}},
 async createInterview(projectId,title,date){const i=await api(`/v1/projects/${projectId}/interviews`,{method:'POST',body:{title,interview_date:date,note:''}});this.interviews.unshift(i);await this.selectInterview(i.id)},
 async saveInterview(i){const saved=await api(`/v1/projects/${i.project_id}/interviews/${i.id}`,{method:'PATCH',body:{title:i.title,note:i.note,interview_date:i.interview_date}});Object.assign(i,saved)},
 async deleteInterview(id=this.currentInterviewId){await api(`/v1/projects/${this.currentProjectId}/interviews/${id}`,{method:'DELETE'});this.interviews=this.interviews.filter(i=>i.id!==id);if(id===this.currentInterviewId){this.currentInterviewId=null;this.segments=[]}},
 async importSegments(rows){const normalized=rows.map((s,index)=>({display_order:index,source_reference:String(s.id??index+1),speaker_label:s.speaker_name||`說話者 ${index+1}`,speaker_role:s.speaker==='interviewer'?'researcher':'participant',text:s.text||'',note:s.note||'',timestamp_ms:s.timestamp??null}));await api(`/v1/projects/${this.currentProjectId}/interviews/${this.currentInterviewId}/segments`,{method:'PUT',body:normalized});await this.selectInterview(this.currentInterviewId)},
 async saveSegments(rows){const body=rows.map(s=>({id:s.id,display_order:s.display_order,source_reference:s.source_reference,speaker_label:s.speaker_name,speaker_role:s.speaker_role,text:s.text,note:s.note,timestamp_ms:s.timestamp_ms}));await api(`/v1/projects/${this.currentProjectId}/interviews/${this.currentInterviewId}/segments`,{method:'PUT',body});await this.selectInterview(this.currentInterviewId)},
 async createCode(body){this.codes.push(await api(`/v1/projects/${this.currentProjectId}/codes`,{method:'POST',body}))},async updateCode(code,changes){Object.assign(code,await api(`/v1/projects/${this.currentProjectId}/codes/${code.id}`,{method:'PATCH',body:changes}))},
 async createCoding(body){const coding=await api(`/v1/projects/${this.currentProjectId}/codings`,{method:'POST',body});this.codings.push(coding);return coding},async deleteCoding(id){await api(`/v1/projects/${this.currentProjectId}/codings/${id}`,{method:'DELETE'});this.codings=this.codings.filter(c=>c.id!==id)},async reconfirmCoding(c,start=c.proposed_start,end=c.proposed_end){const saved=await api(`/v1/projects/${this.currentProjectId}/codings/${c.id}/reconfirm`,{method:'POST',body:{start_offset:start,end_offset:end}});Object.assign(c,saved)},
 async createCase(body){this.cases.push(await api(`/v1/projects/${this.currentProjectId}/cases`,{method:'POST',body}))},async updateCase(c,changes){Object.assign(c,await api(`/v1/projects/${this.currentProjectId}/cases/${c.id}`,{method:'PATCH',body:changes}))},async createAttributeDefinition(body){this.attributeDefinitions.push(await api(`/v1/projects/${this.currentProjectId}/attribute-definitions`,{method:'POST',body}))},async saveCaseAttributes(caseId,values){await api(`/v1/projects/${this.currentProjectId}/cases/${caseId}/attributes`,{method:'PUT',body:values});const c=this.cases.find(x=>x.id===caseId);if(c)c.attributes={...(c.attributes||{}),...values}},async linkSpeaker(interviewId,speakerId,caseId){await api(`/v1/projects/${this.currentProjectId}/interviews/${interviewId}/speakers/${speakerId}`,{method:'PATCH',body:{case_id:caseId}});await this.selectInterview(interviewId)},
 buildSpeakerColorMap(rows){this.speakerColorMap={};let a=0,b=0;for(const s of rows)if(!this.speakerColorMap[s.speaker_name]){const researcher=s.speaker_role==='researcher',palette=researcher?IV_HEX:IE_HEX,index=researcher?a++:b++;this.speakerColorMap[s.speaker_name]={hex:palette[index%palette.length],side:researcher?'left':'right',type:researcher?'interviewer':'interviewee'}}},
 showGlobalLoading(message){this.globalLoading={show:true,message}},hideGlobalLoading(){this.globalLoading={show:false,message:''}},openConfirmModal(title,message,onConfirm,opts={}){this.confirmModal={show:true,title,message,onConfirm,icon:opts.icon||'⚠️',okText:opts.okText||'確認',btnClass:opts.btnClass||'btn-danger'}},closeConfirmModal(){this.confirmModal.show=false;this.confirmModal.onConfirm=null},toast(message,type='success'){useToast().toast(message,type)}
}})
