<template>
  <div v-if="authLoading" class="global-loading"><div class="global-loading-box"><div class="global-loading-spinner"></div><div>驗證登入狀態…</div></div></div>
  <div v-else-if="!user" class="login-page"><div class="login-card"><div class="brand-icon">🎙️</div><h1>QualiStream</h1><p>正式質性研究編碼工作區</p><button class="btn btn-primary" @click="signIn">使用 Google 登入</button><div v-if="configError" class="form-hint error-text">{{ configError }}</div></div></div>
  <div v-else class="app-shell"><AppHeader @logout="signOutUser"/><div class="main-layout"><AppSidebar @open-project-modal="showProjectModal=true" @open-interview-modal="openInterviewModal"/><main class="main-panel"><div class="tab-bar"><button v-for="tab in tabs" :key="tab.id" class="tab-btn" :class="{active:store.activeTab===tab.id}" @click="store.activeTab=tab.id">{{ tab.label }}</button></div><div class="tab-content" style="display:block"><component :is="activeView"/></div></main></div>
    <BaseModal :visible="showProjectModal" title="新增研究專案" @close="showProjectModal=false"><div class="form-group"><label class="form-label">專案名稱</label><input class="form-input" v-model="newProject.name"></div><div class="form-group"><label class="form-label">說明</label><textarea class="form-textarea" v-model="newProject.description"></textarea></div><button class="btn btn-primary" @click="createProject">建立</button></BaseModal>
    <BaseModal :visible="showInterviewModal" title="新增訪談" @close="showInterviewModal=false"><div class="form-group"><label class="form-label">標題</label><input class="form-input" v-model="newInterview.title"></div><div class="form-group"><label class="form-label">日期</label><input type="date" class="form-input" v-model="newInterview.date"></div><button class="btn btn-primary" @click="createInterview">建立</button></BaseModal><ToastContainer/><ConfirmModal/><GlobalLoading/>
  </div>
</template>
<script setup>
import{ref,computed,onMounted}from'vue';import{useAppStore}from'./stores/appStore.js';import{observeAuth,googleSignIn,logout,firebaseConfigured}from'./auth/firebase.js';import{apiConfigured}from'./api/client.js';import{useToast}from'./composables/useToast.js';import AppHeader from'./components/AppHeader.vue';import AppSidebar from'./components/AppSidebar.vue';import BaseModal from'./components/BaseModal.vue';import ToastContainer from'./components/ToastContainer.vue';import ConfirmModal from'./components/ConfirmModal.vue';import GlobalLoading from'./components/GlobalLoading.vue';import ChatTab from'./views/ChatTab.vue';import MetaTab from'./views/MetaTab.vue';import ImportTab from'./views/ImportTab.vue';import AudioTab from'./views/AudioTab.vue';import PromptTab from'./views/PromptTab.vue';import CodebookTab from'./views/CodebookTab.vue';import CasesTab from'./views/CasesTab.vue';import AnalysisTab from'./views/AnalysisTab.vue';import ExportTab from'./views/ExportTab.vue';import SettingsTab from'./views/SettingsTab.vue'
const store=useAppStore(),{toast}=useToast(),user=ref(null),authLoading=ref(true),showProjectModal=ref(false),showInterviewModal=ref(false),targetProject=ref(null),newProject=ref({name:'',description:''}),newInterview=ref({title:'',date:new Date().toISOString().slice(0,10)});const tabs=[{id:'view',label:'💬 編碼逐字稿'},{id:'codebook',label:'🏷️ Codebook'},{id:'cases',label:'👥 Cases'},{id:'analysis',label:'📊 分析'},{id:'export',label:'🔒 匯出'},{id:'meta',label:'📋 訪談'},{id:'import',label:'📥 匯入'},{id:'prompt',label:'✨ 提示詞'},{id:'audio',label:'🎧 音檔'},{id:'settings',label:'⚙️ 設定'}],views={view:ChatTab,codebook:CodebookTab,cases:CasesTab,analysis:AnalysisTab,export:ExportTab,meta:MetaTab,import:ImportTab,prompt:PromptTab,audio:AudioTab,settings:SettingsTab},activeView=computed(()=>views[store.activeTab]||ChatTab),configError=computed(()=>!firebaseConfigured()?'需設定 Firebase frontend 環境變數':!apiConfigured()?'需設定 VITE_API_BASE_URL':'')
onMounted(()=>observeAuth(async value=>{user.value=value;authLoading.value=true;try{if(value)await store.initialize(value)}catch(e){toast('資料載入失敗：'+e.message,'error',6000)}finally{authLoading.value=false}}));async function signIn(){try{await googleSignIn()}catch(e){toast('登入失敗：'+e.message,'error')}}async function signOutUser(){await logout();store.clear()}async function createProject(){if(!newProject.value.name.trim())return;await store.saveProject(newProject.value.name.trim(),newProject.value.description);showProjectModal.value=false;newProject.value={name:'',description:''}}function openInterviewModal(id){targetProject.value=id;showInterviewModal.value=true}async function createInterview(){await store.createInterview(targetProject.value,newInterview.value.title,newInterview.value.date);showInterviewModal.value=false}
</script>
